### ISSUE TITLE
[MSTest] Test class with TestInitlialize method in a base class from a different assembly doesn't run the TestInitialize method

### ISSUE THREAD

**Issue by serbrech** [sdekock/AgUnit#1]
Or so it seems, I'll try to make a sample project to illustrate as soon as I have the time.

**Comment by serbrech** [comment]
Ok, I found out after more investigation that it wasn't agunit not running the testinitialize method in some cases.
MSTest does not instanciate the testclass for each test. and some state setup in the testinitialize was in fact being carried between the different test method of a class. agunit only uncovered it because it didnt run the tests in the same order (due to the base class in a different namespace and resharper sorting them accordingly).

Now question, when we run silverlight tests with the mstest framework. is that using the mstest runner, or a special one?
If we would use the Nunit test adapter for silverlight that is out there. would the nunit test runner be used? in other words, would the runner then instanciate the testclass for each test?
That would be our number one reason to move to nunit or xunit.

**Comment by staxmanade** [comment]
It's true your test class is only initialized once (for all the tests run). However, the [TestInitialize] method should run before each [Test] is run.

Hope this helps.

**Comment by serbrech** [comment]
Indeed it does. It just seemed it didn't at first. Because I got different result in what seemed the same the same context. 
Do you know how the nunit and xunit test provider for silverlight are implemented? Is the class also instanciated only once? Or do they use a different test runner that behaves like the nunit runner which instanciated the class for each test to preserve isolation?

**Comment by staxmanade** [comment]
All those frameworks act the same. Create one instance of the class, and then call the [Test] or [TestMethod] or [Fact] attributed methods.

They also all act the same as far as the setup attributes [SetUp] or [TestInitialize](xunit doesn't because it doesn't have one of those attributes -> SEE xUnit philosophies)

Regarding how they are implemented under the hood... With NUnit StatLight has an NUnit provider for the Microsoft.Silverlight.Testing framework. With xUnit, StatLight uses the "native" xunit contrib silverlight runner.

Hope this helps.

**Comment by serbrech** [comment]
alright, it does help. I did some quick googling on my own and found that xunit does create the test object (the fixture) for each test.

> If we execute the above test cases using the ReSharper plugin, the output would be like below. If you look closely at the output, you can see we are constructing and disposing the test object for EACH TEST. MbUnit\NUnit creates the object once and calls the test methods on the same object. Having an object per test improves the test isolation.
> http://blog.benhall.me.uk/2008/01/introduction-to-xunit.html

while one of the authors of NUnit 2.0, James Newkirk writes:

> I think one of the biggest screw-ups that was made when we wrote NUnit V2.0 was to not create a new instance of the test fixture class for each contained test method. [...] I look back now and see that reusing the instance for each test method allows someone to store a member variable from one test and use it another. This can introduce execution order dependencies which for this type of testing is an anti-pattern. It is much better to fully isolate each test method from the other. This requires that a new object be created for each test method.

I will give a try to the xunit contrib sl runner and see how it behaves. It is so easy to introduce dependencies in the tests without noticing it when you start refactoring your test to use base classes that share some test initializations...

**Comment by staxmanade** [comment]
Appreciate the clarification. Good luck
